### ISSUE TITLE
incompatibility with ffi

### ISSUE THREAD

**Issue by thushw** [asterite/ruby-geohash_int#3]
ffi has updated since this was released. the older ffi that this package depends on has issues on MacOSX/Monterey/12.2.1

This is the error when launching the rails console with ruby-geohash_int gem:

```
thushara@thusharas-MacBook-Pro Pave (geohash)*$ bin/rails c
/Users/thushara/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-fc4d83f43cd3/activesupport/lib/active_support/dependencies.rb:332:in `require': dlopen(/Users/thushara/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.9.25/lib/ffi_c.bundle, 0x0009): symbol not found in flat namespace '_rb_safe_level' - /Users/thushara/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.9.25/lib/ffi_c.bundle (LoadError)
```

I built a new version of ruby-geohash_int for the latest ffi, and would like to submit a PR.

**Comment by jemc** [comment]
Thanks for creating PR #4 to fix this!

It's been merged and released in [geohash_int v0.1.1](https://rubygems.org/gems/geohash_int/versions/0.1.1).

Thanks again for your contribution.
